Exercicios/Exercicios/Controllers/CardapioController.cs
using Exercicios.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Exercicios.Controllers
{
    public class CardapioController : Controller
    {
        private readonly IDbContextFactory<ExerciciosDbContext> context;
        public CardapioController(IDbContextFactory<ExerciciosDbContext> context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var listaCardapios = BuscarTodosCardapios();

            return View(listaCardapios);
        }

       
        public async Task<IActionResult> Create()
        {
            ViewBag.TodasEmpresas = MontarSelect();
            return View();
        }

        [HttpPost]
       
        public async Task<IActionResult> Create(ListarCardapioEmpresaViewModel model)
        {
            CardapioModel cardapio = model;
            cardapio.DataCadastro = DateTime.Now;
            cardapio.Ativo = true;
            using (var contextLocal = context.CreateDbContext())
            {
                cardapio.EmpresaId = contextLocal.Empresas.Where(w => w.Id == cardapio.EmpresaId.Id).First();
                contextLocal.Cardapios.Add(cardapio);
                await contextLocal.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }



        [NonAction]
        private SelectList MontarSelect()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            using (var contextLocal = context.CreateDbContext())
            {
                var empresas = contextLocal.Empresas;

                foreach (var empresa in empresas)
                {
                    list.Add(new SelectListItem
                    {
                        Text = empresa.Descricao,
                        Value = empresa.Id.ToString()
                    });
                }
            }

            return new SelectList(list, "Value", "Text");
        }

        private IEnumerable<ListarCardapioEmpresaViewModel> BuscarTodosCardapios()
        {
            var listarCardapioEmpresaViewModel = new List<ListarCardapioEmpresaViewModel>();

            using (var contextLocal = context.CreateDbContext())
            {
                var cardapios = contextLocal.Cardapios
                            .Include(empresa => empresa.EmpresaId);

                cardapios.ToList().ForEach(cardapios =>
                {
                    listarCardapioEmpresaViewModel.Add(new ListarCardapioEmpresaViewModel
                    {
                        Id = cardapios.Id,
                        Descricao = cardapios.Descricao,
                        Valor = cardapios.Valor,
                        EmpresaId = cardapios.EmpresaId.Id,
                        Ativo = cardapios.Ativo,
                        DescricaoEmpresa = $"{cardapios.EmpresaId.Id} - {cardapios.EmpresaId.Descricao}"

                    });
                });
            }

            return listarCardapioEmpresaViewModel;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ListarCardapioEmpresaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.TodasEmpresas = MontarSelect();
                return View(model);
            }

            using var contextLocal = context.CreateDbContext();

            CardapioModel cardapio = model;
            cardapio.EmpresaId = contextLocal.Empresas.Where(w => w.Id == model.EmpresaId).FirstOrDefault();
            contextLocal.Update(cardapio);
            await contextLocal.SaveChangesAsync();

            return RedirectToAction("Index");

        }
        [Route("cardapio/{id}/Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.TodasEmpresas = MontarSelect();
            using (var contextLocal = this.context.CreateDbContext())
            {
                var ListarCardapioEmpresaViewModel = await contextLocal.Cardapios.Where(w => w.Id == id).FirstOrDefaultAsync();

                if (ListarCardapioEmpresaViewModel == null)
                {
                    
                    return NotFound();
                }

                return View(ListarCardapioEmpresaViewModel);
            }
        }
        [HttpGet]
        [Route("cardapio/{id}/descricao/{descricao}/Delete")]
        public IActionResult Delete(int id, string descricao)
        {
            ViewBag.Id = id;
            ViewBag.Descricao = descricao;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRegistro(int id)
        {
            using var contextLocal = context.CreateDbContext();
            var categoriaModel = await contextLocal.Cardapios.Where(w => w.Id == id).FirstOrDefaultAsync();

            if (categoriaModel == null)
            {
                return NotFound();
            }

            contextLocal.Cardapios.Remove(categoriaModel);
            await contextLocal.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        
    }
}

Exercicios/Exercicios/Controllers/EmpresaController.cs
using Exercicios.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Exercicios.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IDbContextFactory<ExerciciosDbContext> context;
        public EmpresaController(IDbContextFactory<ExerciciosDbContext> context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            using (var contextLocal = context.CreateDbContext())
            {
                return View(await contextLocal.Empresas.ToListAsync());
            }
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmpresaModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            model.DataCadastro= DateTime.Now;
            model.Ativo = true;
            using (var contextLocal = this.context.CreateDbContext())
            {
                contextLocal.Empresas.Add(model);
                await contextLocal.SaveChangesAsync();
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> Edit(int id)
        {
            using (var contextLocal = this.context.CreateDbContext())
            {
                var EmpresaModel = await contextLocal.Empresas.Where(w => w.Id == id).FirstOrDefaultAsync();


                if (EmpresaModel == null)
                {
                    return NotFound();
                }

                return View(EmpresaModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EmpresaModel model)
        {
  
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using var contextLocal = this.context.CreateDbContext();
            if (model.Ativo == false)
            {
                var LocalizacaoModel = await contextLocal.Localizacoes.Where(l => l.EmpresaId == model).FirstOrDefaultAsync();
                LocalizacaoModel.Ativo = false;

            }
 
            contextLocal.Update(model);
            await contextLocal.SaveChangesAsync();

            return RedirectToAction("Index");

        }
        // Falta atender a regra de desativação :Para desativar uma empresa precisa mudar a situação também da Localização e Cardápio
    }
}

Exercicios/Exercicios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exercicios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Exercicios.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exercicios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*Empresa*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Empresa" asp-action="Index">Empresa</a>
                        </li>
                        @*Localizacao*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Localizacao" asp-action="Index">Localizacao</a>
                        </li>
                         @*Cardapio*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cardapio" asp-action="Index">Cardapio</a>
                        </li>
                     </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Exercicios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>